defaults:
  - process: process2
  - model: model1
  - _self_

raw:
  path: data/raw/Employee.csv

processed:
  dir: data/processed
  X_train: ${processed.dir}/X_train.csv
  X_test: ${processed.dir}/X_test.csv
  y_train: ${processed.dir}/y_train.csv
  y_test: ${processed.dir}/y_test.csv

final:
  dir: data/final
  name: final.csv
  path: ${final.dir}/${final.name}

mlflow_tracking_ui: https://dagshub.com/khuyentran1401/employee-future-prediction.mlflow
